"""
    @author: Peter
    @date: 18/08/2024
    @file: message.py
    @description: various messages of reminder, feedback,warning to end user
"""
from enum import Enum


class Message(Enum):
    ADMIN_LOGIN_SUCCESSFUL = "Go to work!!!, Login Successful"
    ADMIN_LOGIN_FAILED = "Don't want to work? Login Failed"
    ADD_CAR_SUCCESSFUL = "The car has been added"
    ADD_CAR_FAILED = "The car has not been added"
    APPLY_COUPON_SUCCESSFUL = "After applying a coupon,you need to pay:"
    APPLY_COUPON_FAILED = "The coupon is invalid,your total rental cost is:"
    COUPON_ADD_SUCCESSFUL = "Coupon added successfully"
    COUPON_ADD_FAILED = "Coupon added failed"
    CUSTOMER_LOGIN_SUCCESSFUL = "Welcome, dear customer, Login Successful"
    CUSTOMER_LOGIN_FAILED = "Sorry, dear customer, Login Failed"
    CAR_NOT_FOUND = "car doesn't exist. Please try again."
    CAR_ORDER_SUCCESSFUL = "Car ordering successful, please wait for auditing!"
    COUPON_APPLIED = "Coupon applied"
    CAR_IS_RENTED = "Car is rented, can not be deleted"
    DELETE_CAR_SUCCESSFUL = "The car has been deleted"
    DELETE_CAR_FAILED = "Delete car failed"
    EXIT_SYSTEM = "Exiting the system. Goodbye!"
    FAILED_TO_PLACE_ORDER = "Failed to place your order. Please try again."
    INVALID_INPUT = "invalid input"
    INVALID_ACTION = "invalid action"
    INVALID_ID = "Invalid id. Please try again."
    INVALID_ORDER_ID = "Invalid order id. Please try again."
    INVALID_DATE_FORMAT = "Invalid date format, Please enter the date in YYYY-MM-DD format."
    INVALID_CHOICE = "Invalid choice. Please try again."
    INPUT_VALID_INTEGER = "Please enter a valid integer."
    INVALID_COUPON_ID = "Invalid coupon id."
    INVALID_COUPON = "Coupon is either expired or not activated."
    INVALID_COUPON_STATUS = "invalid coupon status"
    LICENSE_NO_ALREADY_EXISTS = "license no already exists"
    LOG_OUT = "Logging out...Goodbye"
    LEAVE = "Leaving...Goodbye"
    NOT_EMPTY_USERNAME_OR_PASSWORD = "Username or password cannot be empty."
    NO_PENDING_ORDERS = "No pending orders"
    NO_CHANGE_WITH_NULL = "\n### Only update the input values ###\n"
    NO_COUPONS_FOUND = "No coupons found."
    ORDER_REJECT_FAILED = "order reject failed"
    ORDER_REJECT_SUCCESSFUL = "order reject successful"
    ORDER_APPROVE_FAILED = "order approved failed"
    ORDER_APPROVE_SUCCESSFUL = "order approved successful"
    ORDER_NOT_FOUND = "order not found"
    ORDER_CANCELLED = "Order cancelled."
    PHONE_ALREADY_EXISTS = "phone already exists"
    PASSWORD_MISMATCH = "The two password are not same, sign up failed"
    REGISTRATION_FAILED = "Sign up failed"
    REGISTRATION_SUCCESSFUL = "Sign up successful"
    RENTAL_END_DATE_EARLIER_THAN_START_DATE = "Rental end date cannot be earlier than the start date."
    RENTAL_START_DATE_EARLIER_THAN_PRESENT_DATE = "Rental start date cannot be earlier than the present date."
    RENTAL_DAYS_NOT_AVAILABLE = "The selected car is already rented for the specified dates"
    USERNAME_AND_PASSWORD_LENGTH = "Username must be at least 3 characters and password at least 6 characters long."
    USERNAME_AND_PASSWORD_FORMAT = "Username cannot contain '@' or spaces"
    USERNAME_ALREADY_EXISTS = "user_name already exists"
